{application,server,
	[{description,"echo-server application"},
		{vsn,"1.0.0"},
		{modules,[db_control, ipc_control,
			server_accept_pool, server_accept_pool_sup,
			server_app,
			server_control,
			server_listener,
			server_socket, server_socket_sup,
			server_super_sup,
			server_userlist,
			user_control]},
		{registered,[server_app]},
		{mod,{server_app,[]}},
		{env,[]},
		{applications,[kernel,stdlib]}]}.